### ISSUE TITLE
Gcode parser will remove comments, how can we keep them?

### ISSUE THREAD

**Issue by MicroJoe** [Michael-F-Bryan/gcode-rs#27]
As I am still writing my gcode processor, I am finding out that after parsing and translating gcode all the comments of the initial gcode file are gone. I guess this was wanted because of the `fn skip_comments` in the lexer.

How could I keep the comments? Adding a new entry to `Gcode` seems not appropriate because comments do not have words, etc. However I think parsing the comments may be useful for this usage. I would also like to make the preprocessor add its own comments into the Gcode but it seems impossible either by using the typesystem, I would have to `println!` the comments to stdout directly.

My project can be found here if you need  a concrete example of what I need: https://git.microjoe.org/MicroJoe/emilly/

**Comment by Michael-F-Bryan** [comment]
I think this would be a super useful thing to have! I've seen several machine generated gcode programs in the wild which use comments to pass information to the CNC machine, and I'd like the ability to read that programmatically.

Retaining comments can be kinda annoying though. The thing which makes comments difficult is that they can occur within valid expressions (i.e. between words), as well as on their own. 

So a parser needs to yield items of type gcode or standalone comments, as well as storing a (possibly empty) list of comments inside the gcode. We'd also need to make the `Display` implementation smarter so it prints everything back out in the right order. 


We also need to be usable from `no_std` code, so everything needs to borrow from the original source string and use array backed buffers instead of a normal `Vec`.
